kind: pipeline
name: default

steps:
- name: fetch
  image: docker:git
  commands:
  - git fetch --tags

- name: buildci
  image: golang
  commands:
    - go get ./...
    - go vet ./...
    - go build -o dist/PiwigoDirectoryUploader cmd/PiwigoDirectoryUploader/PiwigoDirectoryUploader.go
    - go test -cover ./...
  when:
    branch: master

- name: buildrelease
  image: golang
  commands:
    - go get ./...
    - build/build-musl.sh
  when:
    event: tag