pipeline:
  build:
    image: golang
    commands:
      - go get ./...
      - go build -o dist/PiwigoDirectoryUploader cmd/PiwigoDirectoryUploader/PiwigoDirectoryUploader.go
      - go test ./...
    when:
      event: [push, tag]
      branch: master
